version: '3'
services:
  app:
    build: .
    ports:
      - 8000:8080
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  redis:
    image: redis:latest
    ports:
      - 6379:6379
